name: source_gen_test
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Elnur Hajiyev <elnurvl@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  annotations:
    path: annotations
  analyzer: ^0.34.0
  build: ^1.0.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  meta: ^1.1.5

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.1.0
  build_test: ^0.10.3
  collection: ^1.14.10
  path: ^1.6.2